version: '3.2'

services:
    library_db:
        image: postgres:14
        restart: always
        container_name: db
        environment:
            - POSTGRES_DB=library_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5434:5432"
        networks:
            - network
    backend:
        image: python:3.8
        container_name: backend
        build: ./library_back
        ports:
            - '8000:8000'
        depends_on:
            - library_db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=library_db
            - POSTGRES_HOST=library_db
            - POSTGRES_PORT=5432
        networks:
            - network
    frontend:
        image: node:13.12.0-alpine
        container_name: frontend
        stdin_open: true
        build: ./library_front
        ports:
            - '3000:3000'
        depends_on:
            - library_db
            - backend  
        networks:
            - network
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - 8080:80
        depends_on:
            - frontend
        networks:
            - network
networks:
    network:
        driver: bridge