version: '3'

services:
    db:
        image: postgres:14
        container_name: db
        environment:
            - POSTGRES_DB=library_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"
        networks:
            - network
    backend:
        image: python:3.9
        container_name: backend
        build: ./library_back
        ports:
            - '8000:8000'
        depends_on:
            - db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=library_db
            - POSTGRES_PORT=5432
        networks:
            - network
    frontend:
        image: node:13.12.0-alpine
        container_name: frontend
        stdin_open: true
        build: ./library_front
        ports:
            - '3000:3000'
        depends_on:
            - db
            - backend  
        networks:
            - network
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - 8080:80
        depends_on:
            - frontend
        networks:
            - network
networks:
  network: