version: '3'

services:
    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_DB=library_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        ports:
            - "5434:5434"
 