version: '3'

services:
    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_DB=library_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"
        networks:
            - library-network
    backend:
        image: python:3
        container_name: backend
        build: ./library_back
        ports:
            - '8000:8000'
        depends_on:
            - db
        networks:
            - library-network
networks:
  library-network: