name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Checkout PyTorch
        uses: actions/checkout@master
      
      - name: Instalacao do lint
        working-directory: ./
        run: pip install flake8

      - name: Run lint back
        working-directory: ./
        run: bash -c "flake8 --max-line-length=200 library_back"

      - name: Run lint front
        working-directory: ./
        run: bash -c "flake8 --max-line-length=200 library_front"
